// <auto-generated />
namespace MishWish.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _001_Added_Tables_MishWishApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_001_Added_Tables_MishWishApp));
        
        string IMigrationMetadata.Id
        {
            get { return "201605281948545_001_Added_Tables_MishWishApp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
